apiVersion: v1
kind: Service
metadata:
  labels: 
    app: techtrends
  name: techtrends 
  namespace: sandbox
spec:
  type: ClusterIP
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends

